import { create } from 'zustand'
import { ARENA_LIMIT, ATTACKS, CONTROLS, GROUND_Y, ROUND_SECONDS } from '../game/constants'
import { boxesOverlap, getAttackHitbox, getHurtbox } from '../game/hitboxes'
import type { AttackType, FighterState, HitSpark, MatchPhase, PlayerId } from '../game/types'
const makeFighter = (id: PlayerId, name: string, modelUrl: string, accent: string, x: number): FighterState => ({ id, name, modelUrl, accent, health: 100, x, y: GROUND_Y, vx: 0, vy: 0, facing: id === 'p1' ? 1 : -1, grounded: true, blocking: false, attack: null, cooldown: 0, dashCooldown: 0, hitStun: 0, blockStun: 0, ko: false, victorious: false })
const fresh = (): Record<PlayerId, FighterState> => ({ p1: makeFighter('p1', 'NEON STRIKER', '/models/fighter-neon.glb', '#54e8ff', -3), p2: makeFighter('p2', 'CRIMSON RIOT', '/models/fighter-crimson.glb', '#ff5267', 3) })
const clamp = (value: number, min: number, max: number) => Math.max(min, Math.min(max, value))
const pressed = new Set<string>(); const tapped = new Set<string>()
type GameStore = { phase: MatchPhase; fighters: Record<PlayerId, FighterState>; timer: number; winner: PlayerId | null; sparks: HitSpark[]; shake: number; debugHitboxes: boolean; nextSparkId: number; startMatch: () => void; rematch: () => void; setKey: (code: string, down: boolean) => void; toggleHitboxes: () => void; update: (delta: number) => void }
const attackTap = (id: PlayerId): AttackType | null => { const c = CONTROLS[id]; return tapped.has(c.special) ? 'special' : tapped.has(c.heavy) ? 'heavy' : tapped.has(c.kick) ? 'kick' : tapped.has(c.light) ? 'light' : null }
const step = (fighter: FighterState, opponent: FighterState, delta: number) => { const c = CONTROLS[fighter.id]; const stunned = fighter.hitStun > 0 || fighter.blockStun > 0; let next = { ...fighter, hitStun: Math.max(0, fighter.hitStun - delta), blockStun: Math.max(0, fighter.blockStun - delta), cooldown: Math.max(0, fighter.cooldown - delta), dashCooldown: Math.max(0, fighter.dashCooldown - delta) }; if (next.ko) { next.vy -= 17 * delta; next.y = Math.max(GROUND_Y, next.y + next.vy * delta); return next } if (next.attack) { const elapsed = next.attack.elapsed + delta; next.attack = elapsed >= ATTACKS[next.attack.type].duration ? null : { ...next.attack, elapsed } } const mayAct = !stunned && !next.attack; const move = (pressed.has(c.right) ? 1 : 0) - (pressed.has(c.left) ? 1 : 0); const tap = attackTap(fighter.id); if (mayAct && tap && next.cooldown <= 0) { next.attack = { type: tap, elapsed: 0, connected: false }; next.cooldown = ATTACKS[tap].cooldown } if (mayAct && !next.attack) { next.blocking = pressed.has(c.block) && next.grounded; if (!next.blocking) { next.vx = move * 3.9; if (tapped.has(c.dash) && next.dashCooldown <= 0) { next.vx = (move || next.facing) * 10; next.dashCooldown = 0.7 } if (tapped.has(c.jump) && next.grounded) { next.vy = 7.6; next.grounded = false } } } next.vy -= 17 * delta; next.x = clamp(next.x + next.vx * delta, -ARENA_LIMIT, ARENA_LIMIT); next.y += next.vy * delta; if (next.y <= GROUND_Y) { next.y = GROUND_Y; next.vy = 0; next.grounded = true } if (!next.attack && !stunned) next.facing = opponent.x >= next.x ? 1 : -1; if (next.attack || stunned) next.vx *= Math.pow(0.12, delta); return next }
const resolve = (attacker: FighterState, defender: FighterState, id: number) => { if (!attacker.attack || attacker.attack.connected) return null; const box = getAttackHitbox(attacker); if (!box || !boxesOverlap(box, getHurtbox(defender))) return null; const spec = ATTACKS[attacker.attack.type]; const blocked = defender.blocking && defender.facing === -attacker.facing && defender.grounded; return { attacker: { ...attacker, attack: { ...attacker.attack, connected: true } }, defender: { ...defender, health: clamp(defender.health - (blocked ? Math.max(1, Math.round(spec.damage * 0.18)) : spec.damage), 0, 100), vx: attacker.facing * spec.knockback * (blocked ? 0.28 : 1), vy: blocked ? defender.vy : spec.knockback * 0.24, hitStun: blocked ? 0 : spec.stun, blockStun: blocked ? spec.blockStun : 0 }, spark: { id, x: box.x, y: box.y, age: 0, life: 0.32, color: blocked ? '#95d7ff' : spec.spark, blocked }, shake: blocked ? 0.12 : 0.3 } }
export const useGameStore = create<GameStore>((set, get) => ({ phase: 'title', fighters: fresh(), timer: ROUND_SECONDS, winner: null, sparks: [], shake: 0, debugHitboxes: false, nextSparkId: 1, startMatch: () => { pressed.clear(); tapped.clear(); set({ phase: 'fight', fighters: fresh(), timer: ROUND_SECONDS, winner: null, sparks: [], shake: 0 }) }, rematch: () => get().startMatch(), setKey: (code, down) => { if (down && !pressed.has(code)) tapped.add(code); down ? pressed.add(code) : pressed.delete(code) }, toggleHitboxes: () => set((state) => ({ debugHitboxes: !state.debugHitboxes })), update: (raw) => { const state = get(); const delta = Math.min(raw, 0.05); const sparks = state.sparks.map((s) => ({ ...s, age: s.age + delta })).filter((s) => s.age < s.life); if (state.phase !== 'fight') { set({ sparks, shake: Math.max(0, state.shake - delta * 2.2) }); tapped.clear(); return } let p1 = step(state.fighters.p1, state.fighters.p2, delta); let p2 = step(state.fighters.p2, p1, delta); let id = state.nextSparkId; let shake = Math.max(0, state.shake - delta * 2.2); const a = resolve(p1, p2, id); if (a) { p1 = a.attacker; p2 = a.defender; sparks.push(a.spark); shake = a.shake; id++ } const b = resolve(p2, p1, id); if (b) { p2 = b.attacker; p1 = b.defender; sparks.push(b.spark); shake = b.shake; id++ } const timer = Math.max(0, state.timer - delta); let phase: MatchPhase = 'fight'; let winner: PlayerId | null = null; if (p1.health <= 0 || p2.health <= 0 || timer <= 0) { winner = p1.health >= p2.health ? 'p1' : 'p2'; phase = 'ko'; p1 = { ...p1, ko: winner !== 'p1', victorious: winner === 'p1' }; p2 = { ...p2, ko: winner !== 'p2', victorious: winner === 'p2' } } set({ fighters: { p1, p2 }, timer, phase, winner, sparks, shake, nextSparkId: id }); tapped.clear() } }))
