import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { Suspense, useMemo, useRef } from 'react'
import * as THREE from 'three'
import { ATTACKS } from '../game/constants'
import { getAttackHitbox, getHurtbox } from '../game/hitboxes'
import type { PlayerId } from '../game/types'
import { useGameStore } from '../store/gameStore'
const Skin = ({ modelUrl }: { modelUrl: string }) => { const { scene } = useGLTF(modelUrl); const skin = useMemo(() => { const clone = scene.clone(true); clone.traverse((child) => { if (child instanceof THREE.Mesh) { child.castShadow = true; child.receiveShadow = true } }); return clone }, [scene]); return <primitive object={skin} /> }
const LoadingSkin = ({ accent }: { accent: string }) => <mesh position={[0, 1.2, 0]} castShadow><boxGeometry args={[0.8, 2.25, 0.52]} /><meshStandardMaterial color={accent} /></mesh>
const DebugBoxes = ({ id }: { id: PlayerId }) => { const fighter = useGameStore((state) => state.fighters[id]); const enabled = useGameStore((state) => state.debugHitboxes); if (!enabled) return null; const hurtbox = getHurtbox(fighter); const hitbox = getAttackHitbox(fighter); return <><mesh position={[hurtbox.x - fighter.x, hurtbox.y - fighter.y, 0.1]}><boxGeometry args={[hurtbox.width, hurtbox.height, 0.3]} /><meshBasicMaterial color="#49dfff" wireframe /></mesh>{hitbox && <mesh position={[hitbox.x - fighter.x, hitbox.y - fighter.y, 0.2]}><boxGeometry args={[hitbox.width, hitbox.height, 0.34]} /><meshBasicMaterial color="#ff5a36" wireframe /></mesh>}</> }
export const FighterController = ({ id }: { id: PlayerId }) => { const root = useRef<THREE.Group>(null); const skin = useRef<THREE.Group>(null); const fighter = useGameStore((state) => state.fighters[id]); useFrame(({ clock }) => { if (!root.current || !skin.current) return; const current = useGameStore.getState().fighters[id]; const idle = Math.sin(clock.elapsedTime * 4.2 + (id === 'p1' ? 0 : 1.4)); root.current.position.set(current.x, current.y, 0); root.current.rotation.set(0, current.facing === 1 ? 0 : Math.PI, 0); skin.current.position.set(0, idle * 0.035, 0); skin.current.rotation.set(0, 0, current.ko ? -current.facing * Math.PI * 0.48 : current.hitStun > 0 ? 0.22 : 0); skin.current.scale.setScalar(current.victorious ? 1.06 : 1); if (current.attack) { const pulse = Math.sin(current.attack.elapsed / ATTACKS[current.attack.type].duration * Math.PI); skin.current.position.x = pulse * 0.36; if (current.attack.type === 'kick') skin.current.rotation.y = pulse * Math.PI * 1.65; if (current.attack.type === 'special') skin.current.scale.setScalar(1 + pulse * 0.14) } }); return <group ref={root}><group ref={skin}><Suspense fallback={<LoadingSkin accent={fighter.accent} />}><Skin modelUrl={fighter.modelUrl} /></Suspense></group><DebugBoxes id={id} /></group> }
useGLTF.preload('/models/fighter-neon.glb'); useGLTF.preload('/models/fighter-crimson.glb')
